---
- hosts: all
  become: true
  vars_files:
    - .vault
  vars:
    - msg_title: "Apt updates & upgrades done"
  tasks:
    - name: Run update
      ansible.builtin.apt:
        update_cache: true
        autoremove: yes
        upgrade: safe
  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ pushover_app_id }}"
        user_key: "{{ pushover_user_id }}"
        msg: "{{ msg_title }}"
        pri: 0
      delegate_to: localhost
