---
- name: Finding and removing old files
  hosts: jupiter
  gather_facts: false
  vars_files:
    - .vault
  tasks:
    - name: Find the files older than 10 days
      become: true
      ansible.builtin.find:
        path: /u/backups/
        age: 10d
        recurse: true
      register: file_list
    - name: Find directories older than 10 days
      ansible.builtin.find:
        path: /u/backups/
        age: 10d
        file_type: directory
      register: dir_list
    - name: Delete old files
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ file_list.files }}"
      delegate_to: "{{ ansible_host }}"
    - name: Delete the old directories too
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ dir_list.files }}"
      notify: 
        - Push over

  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ pushover_app_id }}"
        user_key: "{{ pushover_user_id }}"
        msg: "Delete old backup files and directories - complete"
        pri: 0
      delegate_to: localhost
