---
- name: Finding and removing old files
  hosts: jupiter
  gather_facts: false
  vars_files:
    - .vault
  become: true
  tasks:
    - name: Find directories older than 10 days
      ansible.builtin.find:
        path: /u/backups/
        age: 10d
        file_type: directory
        follow: false
        recurse: true
        get_checksum: false
        hidden: false
        patterns: '[*]'
        use_regex: false
      register: dir_list
    - name: Delete the old directories too
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
        follow: false
        get_checksum: false
        hidden: false
        recurse: true
      register: dir_list
      loop: "{{ dir_list.files }}"
      notify: 
        - Push over

  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ pushover_app_id }}"
        user_key: "{{ pushover_user_id }}"
        msg: "Delete old backup files and directories - complete"
        pri: 0
      delegate_to: localhost
