---
- name: Finding and removing old files
  hosts: jupiter
  gather_facts: false
  vars_files:
    - .vault
  vars:
    - msg_title: "Deleted files older than 10 days"
  tasks:
    - name: Find the files older than 10 days
      become: true
      ansible.builtin.find:
        path: /u/backups/
        age: 10d
        recurse: true
      register: msg_text
    - name: Delete old files
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{  msg_text.files  }}"
      delegate_to: "{{  ansible_host  }}"
      notify: 
        - Push over

  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ pushover_app_id }}"
        user_key: "{{ pushover_user_id }}"
        msg: "{{ msg_title }}"
        pri: 0
      delegate_to: localhost
