---
- name: Backup do
  hosts: live
  vars:
    archive_tag: "{{ ansible_date_time.date.replace('-','') }}"
    backup_dir: "/var/ansible/data/{{ archive_tag }}"
    backup_targets:
      - /etc
      - /home/camille
#      - /etc/nginx/conf.d/
#      - /home/www
  vars_files:
    - .vault

  tasks:
    - name: Create backup dir
      become: true
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
      tags:
        - mk_dir

    - name: Archive files
      become: true
      community.general.archive:
        path: "{{ item }}"
        exclusion_patterns:
          - '**/*tar.gz'
          - '**/*tgz'
          - '**/*deb'
          - '**/*zip'
          - '**/*tar'
          - '**/*misskey*'
        dest: "{{ backup_dir }}/{{ item.rsplit('/')[-1] }}-{{ archive_tag }}.tgz"
      loop: "{{ backup_targets }}"
      tags:
        - archiving
      register: archive_output
      notify: 
        - Push over

    - name: Change ownership of archive directory
      become: true
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        owner: "{{ ansible_user }}"
        recurse: true
      tags:
        - chowning

    - name: Get list of files
      ansible.builtin.find:
        path: "{{ backup_dir }}"
        patterns: "*"
      register: file_list
      tags:
        - finding

    - name: Copy to DO
      amazon.aws.aws_s3:
        aws_access_key: "{{ vault_do_access_key }}"
        aws_secret_key: "{{ vault_do_secret_key }}"
        s3_url: '{{ vault_s3_url }}'
        region: '{{ vault_s3_region }}'
        bucket: '{{ vault_s3_bucket }}'
        object: "/do/{{ archive_tag }}/{{ item.path | basename }}"
        src: "{{ item.path }}"
        mode: put
        overwrite: no
      with_items: "{{ file_list.files }}"
      tags:
        - s3copying
      register: s3copy_output
      notify:
        - Push over

  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ vault_pushover_app_id }}"
        user_key: "{{ vault_pushover_user_id }}"
        msg: "Backup completed for DO {{ ansible_date_time.date }}"
        pri: 0
