---
- name: Backup do
  hosts: live
  vars_files:
    - .vault
  vars:
    archive_tag: "{{ ansible_date_time.date.replace('-','') }}"
    backup_dir: "{{ vault_do_backup_dest }}/{{ archive_tag }}"

  tasks:
    - name: Create backup dir
      become: true
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
      tags:
        - make_dir

    - name: Archive files
      become: true
      community.general.archive:
        path: "{{ item }}"
        exclusion_patterns:
          - '**/*tar.gz'
          - '**/*tgz'
          - '**/*deb'
          - '**/*zip'
          - '**/*tar'
          - '**/*misskey*'
          - '**/*iso'
        dest: "{{ backup_dir }}/{{ item.rsplit('/')[-1] }}-{{ archive_tag }}.tgz"
      loop: "{{ vault_do_backup_targets }}"
      tags:
        - archiving
      register: archive_output
      notify: 
        - Push over

    - name: Dump YOURLS database
      community.docker.docker_container_exec:
        container: urls-db
        argv:
          - "mysqldump"
          - "--password={{ vault_urls_db_root_password }}"
          - "yourls"
          - "--result-file=/tmp/yourls.sql"
      tags:
        - yourls_db_dump

    - name: Copy YOURLS database dump to host
      become: true
      ansible.builtin.shell: "docker cp urls-db:/tmp/yourls.sql {{ backup_dir }}/yourls-{{ archive_tag }}.sql"
      tags:
        - docker_cp

    - name: Change ownership of archive directory
      become: true
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        owner: "{{ ansible_user }}"
        recurse: true
      tags:
        - chowning

    - name: Copy to DO
      with_fileglob: "{{ backup_dir }}/*"
      amazon.aws.aws_s3:
        aws_access_key: "{{ vault_do_access_key }}"
        aws_secret_key: "{{ vault_do_secret_key }}"
        s3_url: '{{ vault_s3_url }}'
        region: '{{ vault_s3_region }}'
        bucket: '{{ vault_s3_bucket }}'
        object: "{{ vault_do_s3_dest }}/{{ archive_tag }}/{{ item.path | basename }}"
        src: "{{ item.path }}"
        mode: put
        overwrite: no
      tags:
        - s3copy
      register: s3copy_output
      notify:
        - Push over

  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ vault_pushover_app_id }}"
        user_key: "{{ vault_pushover_user_id }}"
        msg: "Backup completed for DO {{ ansible_date_time.date }}"
        pri: 0
