---
- name: Touch the target archive file for joplin db dump
  ansible.builtin.file:
    path: "{{ backup_dir }}/{{ archive_tag }}-joplin.sql"
    state: touch
    follow: true
  tags: create_psql_output
  when: do_joplin

- name: Dump a database in a docker container
  community.docker.docker_container_exec:
    container: joplin-db
    argv:
      - pg_dump
      - --dbname=joplin
      - --username=joplin
      - --file=/tmp/{{ archive_tag }}-joplin.sql
  tags: psql_dump
  register: dump_output
  when: do_joplin

- name: Copy dump to host
  ansible.builtin.shell: docker cp joplin-db:/tmp/{{ archive_tag }}-joplin.sql {{ backup_dir }}
  register: dockertohost_output
  tags: docker_cp
  when: do_joplin
