---
- name: Nightly backups
  hosts: local,remote
  vars_files:
    - .vault
    - .backupVars
  become: true
  tasks:
    - include_tasks: archive.yaml
    - include_tasks: joplinDBDump.yaml
    - include_tasks: mysqlDump.yaml
    - include_tasks: s3copy.yaml
