---
- name: Nightly backups
  hosts: "{{ variable_host | default('remote,local')}}"
  vars_files:
    - .vault
    - .backupVars
  become: true
  tasks:
    - ansible.builtin.include_tasks: archive.yaml
    - ansible.builtin.include_tasks: joplinDBDump.yaml
    - ansible.builtin.include_tasks: mysqlDump.yaml
    - ansible.builtin.include_tasks: s3copy.yaml
    - name: Remove backup directory to save space
      ansible.builtin.file:
        path: '{{ backup_dir }}'
        state: absent

  handlers:
    - name: Push over
      community.general.pushover:
        app_token: "{{ pushover_app_id }}"
        user_key: "{{ pushover_user_id }}"
        msg: "Nightly backup completed for {{ ansible_date_time.date }}"
        pri: 0
