---
- name: Testing
  hosts: localhost
  vars_files: .vault
  vars_prompt:
    - name: username
      prompt: "What is your username?"
      private: false
    - name: email
      prompt: "Enter your email?"
      private: false
  tasks:
    - name: Output
      ansible.builtin.debug:
        msg: "{{ username }} and {{ email }}"
