---
- name: Set lifecycle rules for DO spaces
  hosts: jupiter
  vars_files:
    - .vault

  tasks:
    - name: Get current lifecycle rules
      community.aws.s3_lifecycle:
        aws_access_key: "{{ do_access_key }}"
        aws_secret_key: "{{ do_secret_key }}"
        endpoint_url: "{{ s3_url }}"
        region: "{{ s3_region }}"
        name: "{{ s3_bucket }}"
        prefix: "/do2"
        state: present
        rule_id: misskey_backup_lifecycle
        expiration_days: 15
