---
- name: Manage DigitalOcean Spaces ACLs
  hosts: localhost
  vars_files:
    - .vault

  tasks:
    - name: Get current ACLs
      amazon.aws.s3_object:
        aws_access_key: "{{ do_access_key }}"
        aws_secret_key: "{{ do_secret_key }}"
        endpoint_url: "{{ s3_url }}"
        region: "{{ s3_region }}"
        bucket: "{{ s3_bucket }}"
        prefix: "/i"
        permission: list
        mode: get
